---
title: "Makroanalyse medicinpriser"
author: "Lars Børty"
date: "14/9/2019"
output:
  html_document:
    code_folding: hide
    theme: flatly
    toc: yes
    toc_float:
      collapsed: no
---


```{r message=FALSE, warning=FALSE}
#devtools::install_github("mikkelkrogsholm/statsDK")
library(tidyverse)
library(eurostat)
library(RColorBrewer)
library(sf)
library(patchwork)
library(ggthemes)
library(statsDK)
library(scales)
library(knitr)
library(kableExtra)
library(xtable)

CO   <- c("UK","DK","NO","SE","DE","FR","NL")
pal4 <- colorRampPalette(brewer.pal(4, "Paired"))
palblue <- colorRampPalette(brewer.pal(1, "Paired"))
pal1 <- ggthemes_data[["tableau"]][["color-palettes"]][["regular"]]$`Classic 10`
pal2 <- ggthemes_data[["tableau"]][["color-palettes"]][["regular"]]$`Classic 20`


th  <-                   theme(panel.grid.major   = element_blank(), panel.grid.minor = element_blank())
th2 <- theme_minimal() + theme(panel.grid.major.y = element_blank(), panel.grid.minor = element_blank())
th1 <- theme_minimal() + theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
```



```{r}
atc_names <- c("A: Alimentary tract\nand metabolism", 
               "B: Blood and blood\nforming organs", 
               "C: Cardiovascular\nsystem", 
               "D: Dermatologicals", 
               "G: Genito-urinary\nsystem and sex hormones", 
               "H: Systemic hormonal\npreparations", 
               "J: Antiinfectives for\nsystemic use", 
               "L: Antineoplastic and\nimmunomodulating agents", 
               "M: Musculo-skeletal\nsystem", 
               "N: Nervous system", 
               "P: Antiparasitic products\ninsecticides and repellents", 
               "R: Respiratory\nsystem", 
               "S: Sensory organs", 
               "V: Various")
```



```{r message=FALSE, warning=FALSE}
atc_codes <- read_delim("external_data/medstat/atc_code_text.txt", 
    ";", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE) %>% 
  rename(atc_code = X1, name = X2) %>% 
  select(atc_code, name) %>% 
  mutate(name = if_else(str_detect(atc_code, "[*]"), atc_code, name)) %>% 
  group_by(atc_code) %>% 
  summarize(name = first(name)) %>% 
  mutate(name = str_extract(name, "[^,]+"))

save(atc_codes, file="generated_data/atc_codes.rdata")
```






```{r message=FALSE, warning=FALSE}

data <- NULL

for (i in 1996:2019) {
  
prod_data <- read_delim(paste0("external_data/medstat/",i,"_product_name_data.txt"), 
    ";", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

names(prod_data) <- c("atc_code",
                      "year",
                      "sector",
                      "product_id",
                      "a1_sold_packs",
                      "a1_sold_amount",
                      "a1_turnover",
                      "a2_sold_packs",
                      "a2_sold_packs_supp",
                      "a2_sold_amounts",
                      "a2_turnover",
                      "a2_regional_sup",
                      "a3_sold_packs",
                      "a3_sold_amounts",
                      "unknown")

data <- rbind(data, prod_data)
}

table(data$year)

```

```{r}
defl <- statsDK::sdk_retrieve_data("PRIS112") %>% 
  filter(HOVED == "Average, yearly",
         between(TID, 1996, 2019)) %>% 
  mutate(index = as.numeric(INDHOLD)/102.2)

data <- data %>% left_join(defl, by=c("year"="TID")) %>% 
  mutate(cost_adj = a1_turnover/index)
```

```{r}
a <- data %>% filter(sector==200) %>% 
  filter(year%in%c(2018,1997)) %>% 
  #filter(substr(atc_code,1,1)=="L") %>% 
  group_by(year) %>% 
  summarize(tsum = sum(cost_adj, na.rm=T)*0.8)
((a[[2,2]]-a[[1,2]])/a[[1,2]])*100 # total growth
((a[[2,2]]/a[[1,2]])^(1/21)-1)*100 # growth per year
```



```{r}
data %>% filter(sector==200) %>% 
  group_by(year) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)*0.8) %>% 
  arrange(desc(sum))

data %>% filter(sector==200) %>% 
  filter(year==2018) %>% 
  group_by(atc_code) %>% 
  summarize(tsum = sum(cost_adj)) %>% 
  arrange(desc(tsum)) %>% 
  mutate(csum = cumsum(tsum),
         pct  = csum/sum(tsum, na.rm=T),
         nn = row_number())
```


```{r fig.height=3, fig.width=10}
# Number of drugs that compose n% of the expenses
me1 <- data %>% 
  filter(sector==200) %>% 
  group_by(atc_code, year) %>% 
  summarize(tsum = sum(cost_adj, na.rm=T)) %>% 
  group_by(year) %>% 
  arrange(desc(tsum)) %>% 
  mutate(csum = cumsum(tsum),
         pct  = csum/sum(tsum, na.rm=T),
         nn = row_number()) %>%
  group_by(year) %>% 
  mutate(type = case_when(abs(pct-0.50) == min(abs(pct-0.50)) ~ "50%",
                          abs(pct-0.25) == min(abs(pct-0.25)) ~ "25%",
                          abs(pct-0.75) == min(abs(pct-0.75)) ~ "75%",
                          abs(pct-0.85) == min(abs(pct-0.85)) ~ "85%"
                          )) %>% 
  filter(!is.na(type)) %>% 
  ggplot(aes(year, nn, color=type)) + 
  geom_line(size=1.5) + 
  geom_point(size = 1, shape=21, stroke=2.5, fill="white") +
  scale_color_manual(values=palblue(5)[1:4]) +
  scale_x_continuous(breaks=c(seq(1997,2018, by=3))) +
  guides(color = guide_legend(reverse = TRUE)) +
  geom_text(aes(label=nn), nudge_y = 8, show.legend = F, size=3)+
  labs(title=NULL, y="n",x=NULL, 
       caption = "Source: Medstat", color="Percentage") + theme_minimal() + 
  theme(panel.grid.major.y = element_blank(), panel.grid.minor = element_blank())
me1
```

```{r}
me2a <- data %>% filter(sector==200) %>% 
  group_by(year, cod =substr(atc_code, 1,1)) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  arrange(desc(sum)) %>%  
  ggplot(aes(year, (sum/1000000)*0.8, fill=cod)) + 
  geom_col(show.legend = T, color=NA, width=0.8)+ 
  scale_fill_manual(values=pal4(16), labels=atc_names) +
  scale_y_continuous(breaks=seq(0,14,1),label = unit_format(unit = "b", sep = "", accuracy = 1)) +
  scale_x_continuous(breaks=seq(1997,2019,2)) +
  labs(title=NULL, y="DKK", x=NULL, fill="ATC group", caption="Source: Medstat + adjusted for inflation ~ DST") + th1 +
  coord_cartesian(ylim=c(0.3,9)) +
  theme(legend.key.height=unit(1.4,"line"),
        legend.key.width =unit(0.6,"line"),
        legend.text=element_text(size=8))
me2a

me2b <- data %>% filter(sector==101) %>% 
  group_by(year, cod =substr(atc_code, 1,1)) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  arrange(desc(sum)) %>%  
  ggplot(aes(year, (sum/1000000)*0.8, fill=cod)) + 
  geom_col(show.legend = T, color=NA)+ 
  scale_fill_manual(values=pal4(16), labels=atc_names) +
  scale_y_continuous(breaks=seq(0,10,1),label = unit_format(unit = "b", sep = "", accuracy = 1)) +
  scale_x_continuous(breaks=seq(1997,2018,3)) +
  labs(title=NULL, y="DKK", x=NULL, fill="ATC group", caption="Source: Medstat + adjusted for inflation ~ DST") + th1 +
  coord_cartesian(ylim=c(0.3,10.7)) +
  theme(legend.key.height=unit(1.4,"line"),
        legend.key.width =unit(0.6,"line"),
        legend.text=element_text(size=8))
me2b
```



```{r fig.height=4.5, fig.width=10}
pa1 <- data %>% filter(sector==200) %>% 
  group_by(year, cod =substr(atc_code, 1,1)) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  arrange(desc(sum)) %>%  
  ggplot(aes(year, (sum/1000000), fill=cod)) + 
  geom_col(show.legend = F, color=NA, width=0.9)+ 
  scale_fill_manual(values=pal4(16), labels=atc_names) +
  scale_y_continuous(breaks=seq(0,14,1), limits=c(0,13.1),label = unit_format(unit = "b", sep = "", accuracy = 1)) +
  scale_x_continuous(breaks=seq(1997,2018,3)) +
  labs(title=NULL, y="DKK", x=NULL, fill="ATC group") + th1 +
  facet_wrap(~"Hospital medication") +
  coord_cartesian(ylim=c(0.6,13)) +
  theme(legend.key.height=unit(1.4,"line"),
        legend.key.width =unit(0.6,"line"),
        legend.text=element_text(size=8))

pa2 <- data %>% filter(sector==101) %>% filter(year>1996) %>%  
  group_by(year, cod =substr(atc_code, 1,1)) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  arrange(desc(sum)) %>%  
  ggplot(aes(year, (sum/1000000), fill=cod)) + 
  geom_col(show.legend = T, color=NA, width=0.9)+ 
  scale_fill_manual(values=pal4(16), labels=atc_names) +
  scale_y_continuous(breaks=seq(0,14,1), limits=c(0,13.1),label = unit_format(unit = "b", sep = "", accuracy = 1)) +
  scale_x_continuous(breaks=seq(1997,2018,3)) +
  labs(title=NULL, x=NULL, fill="ATC group", caption="Source: Medstat + adjusted for inflation ~ DST", y=NULL) + th1 +
  facet_wrap(~"Prescription medication") +
  coord_cartesian(ylim=c(0.6,13)) +
  theme(legend.key.height=unit(1.4,"line"),
        legend.key.width =unit(0.6,"line"),
        legend.text=element_text(size=8))

me2 <- pa1 + pa2 + plot_layout(guides = "collect") & theme(legend.text=element_text(size=7))
me2

```






```{r fig.height=6.5, fig.width=12}
p1 <- data %>% filter(sector==200) %>% 
  group_by(year, cod =substr(atc_code, 1,1)) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  arrange(desc(sum)) %>%  
  ggplot(aes(year, (sum/1000000)*0.8, fill=cod)) + 
  geom_col(show.legend = T, color=NA)+ 
  scale_fill_manual(values=pal4(16), labels=atc_names) +
  scale_y_continuous(breaks=seq(0,14,1), limits=c(0,10)) +
  scale_x_continuous(breaks=seq(1997,2018,2)) +
  labs(title="", y="bDKK", x=NULL, fill="ATC group") + 
  theme(legend.key.height=unit(1.7,"line"),
        legend.key.width =unit(0.8,"line"),
        legend.text=element_text(size=8)) + facet_wrap(~"Hospital Medication\nby atc-code") +
  th

p2 <- data %>% filter(sector==200) %>% 
  filter(substr(atc_code, 1,1)=="L") %>% 
  group_by(year, cod =substr(atc_code, 1,3)) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  mutate(cod = case_when(cod == "L01" ~ "L01\nAntineoplastic agents",
                         cod == "L02" ~ "L02\nEndocrine therapy",
                         cod == "L03" ~ "L03\nImmunostimulants",
                         cod == "L04" ~ "L04\nImmunosuppressants")) %>% 
  arrange(desc(sum)) %>%  
  ggplot(aes(year, (sum/1000000)*0.8)) + 
  geom_col(show.legend = T, color=NA, width=0.8)+ 
  scale_y_continuous(breaks=seq(0,12,1)) +
  scale_x_continuous(breaks=seq(1997,2018,4)) +
  labs(title="", y="bDKK", x=NULL, fill="ATC group",caption="Source: Medstat + adjusted for inflation ~ DST") + 
  theme(legend.key.height=unit(1.7,"line"),
        legend.key.width =unit(0.8,"line"),
        legend.text=element_text(size=8)) + facet_wrap(~cod, ncol=1) + 
  th

me3 <- p1 + p2 + plot_layout(widths = c(3,1.5))
me3
```













```{r fig.height=7, fig.width=12}
ttemp <- data %>% 
  full_join(atc_codes, by="atc_code") %>% 
  filter(sector==200) %>% 
  filter(substr(atc_code, 1,3)%in%c("L01","L04")) %>% 
  group_by(name) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  filter(sum>1300000) %>% 
  select(name) %>% 
  mutate(ccol = "yes")

temp <- data %>% 
  full_join(atc_codes, by="atc_code") %>% 
  filter(sector==200) %>% 
  filter(substr(atc_code, 1,3)%in%c("L01","L04")) %>% 
  group_by(year, name) %>% 
  summarize(sum = sum(cost_adj, na.rm=T)) %>% 
  group_by(year) %>% 
  mutate(rankk = rank(-sum)) %>% 
  filter(rankk <26)  %>% 
  left_join(ttemp, by="name") %>% 
  mutate(ccode = if_else(is.na(ccol), NA_character_, name))

me5 <- temp %>% 
  ggplot(aes(year, rankk, group=name, color=ccode)) + 
  geom_line(show.legend = F, size=1.5, alpha=0.6) + 
  geom_point(size = 2.5, shape=21, stroke=2.5, fill="white",show.legend = F) +
  scale_color_manual(values=c(rev(pal1$value),"black"),na.value="grey") +
  scale_x_continuous(breaks=seq(1997,2019,2)) +
  geom_text(data=subset(temp, year==2019), aes(label=name, x=year+0.3), size=4, show.legend = F, fontface = "bold", hjust = "left") +
  geom_text(data=subset(temp, year==1997), aes(label=name, x=year-0.3), size=4, show.legend = F, fontface = "bold", hjust = "right") +
  labs(title=NULL, y=NULL, x=NULL, caption="Source: Medstat") + 
  theme(legend.key.height=unit(1.7,"line"),
        legend.key.width =unit(0.8,"line"),
        legend.text=element_text(size=8)) + 
  scale_y_reverse(breaks = c(1:25), limits=c(25,1)) + 
  coord_cartesian(xlim=c(1995,2021)) +
  theme_minimal() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
me5
```







```{r fig.height=5, fig.width=12}
yr <- data %>% filter(sector==200) %>% group_by(atc_code) %>% summarize(year = first(year))

pa1 <- data %>% filter(sector==200) %>% 
  full_join(atc_codes, by="atc_code") %>% 
  group_by(name) %>% 
  summarize(sum = sum(a1_turnover, na.rm=T), 
            atc_code = first(atc_code)) %>% 
  top_n(n = 25, wt = sum) %>% 
  left_join(yr, by="atc_code") %>% 
  ggplot(aes(reorder(name,sum), (sum/1000)*0.8, fill=year)) + 
  geom_col(width = 0.8) + 
  coord_flip() + 
  scale_fill_distiller("Year\nintroduced", limits=c(1997,2019), direction = 1,values = c(-0.5,1)) + 
  labs(title="Most costly drug since 1996", x=NULL, y="mDKK") + 
  theme_minimal() + 
  theme(panel.grid.major.y = element_blank(), panel.grid.minor = element_blank())

pa2 <- data %>% filter(sector==200, year==2019) %>% 
  full_join(atc_codes, by="atc_code") %>% 
  group_by(name) %>% 
  summarize(sum = sum(a1_turnover, na.rm=T), atc_code=first(atc_code)) %>% 
  top_n(n = 25, wt = sum) %>% 
  left_join(yr, by="atc_code") %>% 
  ggplot(aes(reorder(name,sum), (sum/1000)*0.8, fill=year)) + 
  geom_col(width = 0.8) + 
  coord_flip() + 
  scale_fill_distiller("Year\nintroduced", limits=c(1997,2019), direction = 1,values = c(-0.5,1)) + 
  labs(title="Most costly drugs in 2018", x=NULL, y="mDKK", caption="Source: Medstat") + 
  theme_minimal()+ 
  theme(panel.grid.major.y = element_blank(), panel.grid.minor = element_blank())

me6 <- pa1 + pa2 + plot_layout(guides="collect")
me6
```







```{r fig.height=7, fig.width=12}
top <- data %>% filter(sector==200) %>% 
  full_join(atc_codes, by="atc_code") %>% 
  group_by(name) %>% 
  summarize(sum = sum(a1_turnover, na.rm=T)) %>% 
  top_n(n = 28, wt = sum) %>% 
  select(name)

me7 <- data %>% filter(sector==200) %>% 
  full_join(atc_codes, by="atc_code") %>% 
  filter(name %in% top$name) %>% 
  group_by(name, year) %>% 
  summarize(sum = sum(a1_turnover, na.rm=T)) %>% 
  ggplot(aes(year, (sum/1000)*0.8)) + 
  geom_line() + 
  geom_ribbon(aes(ymin=0, ymax=(sum/1000)*0.8), alpha=0.3) +
  facet_wrap(~reorder(name, desc(sum)), nrow=4) +
  labs(title="Hospital medication", y="mDKK",x=NULL) + th

me7

#top <- data %>% filter(sector==101) %>% 
#  full_join(atc_codes, by="atc_code") %>% 
#  group_by(name) %>% 
#  summarize(sum = sum(a1_turnover, na.rm=T)) %>% 
#  top_n(n = 32, wt = sum) %>% 
#  select(name)
#
#data %>% filter(sector==101) %>% 
#  full_join(atc_codes, by="atc_code") %>% 
#  filter(name %in% top$name) %>% 
#    filter(!(atc_code %in% c("N04BA02","G03FB05","G03FA01"))) %>% 
#  group_by(name, year) %>% 
#  summarize(sum = sum(a1_turnover, na.rm=T)) %>% 
#  ggplot(aes(year, (sum/1000)*0.8)) + 
#  geom_line() + 
#  geom_ribbon(aes(ymin=0, ymax=(sum/1000)*0.8), alpha=0.3) +
#  facet_wrap(~reorder(name, desc(sum)), nrow=4) +
#  labs(title="Prescription medication", y="mDKR",x=NULL)
```


```{r fig.height=6, fig.width=12}
df1 <- data %>% 
  filter(sector %in% c(200,101)) %>% 
  group_by(cod = substr(atc_code, 1,1), sector) %>% 
  summarize(sum = round(sum(a1_sold_amount, na.rm=T)/1e3,1)) %>% 
  arrange(desc(sum)) %>% 
  spread(key = sector, value = sum)
names(df1) <- c("cod","Prescription medication","Hospital medication")
df1$Name <- atc_names
df1$cod <- NULL
df1 <- df1 %>% 
  ungroup() %>% 
  bind_rows(tibble("Name"="Total", 
                   "Prescription medication" = sum(df1$`Prescription medication`), 
                   "Hospital medication" = sum(df1$`Hospital medication`)))

#df1[,c(3,1,2)] %>% kable() %>% kable_styling()
print(xtable(df1[,c(3,1,2)], type = "latex", booktabs = T, digits = 1), file = "latex_tables/tab1.tex")
```









```{r fig.height=4.5, fig.width=12}
df <- data %>% filter(sector%in%c(101,200)) %>% 
  filter(year!=1996) %>% 
  group_by(atc_code, year, sector) %>% 
  summarize(cost = sum(cost_adj, na.rm=T)) %>% 
  group_by(atc_code, sector) %>% 
  mutate(atc_year=min(year)) %>% 
  left_join(atc_codes, by="atc_code") %>% 
  group_by(year, atc_year, atc_code, name, sector) %>% 
  summarize(cost=sum(cost, na.rm=T)) %>% 
  ungroup() %>% 
  mutate(atc_year = case_when(    atc_year< 1998       ~ "Before 1998",
                          between(atc_year, 1998,2000) ~ "1998-2000",
                          between(atc_year, 2001,2003) ~ "2001-2003",
                          between(atc_year, 2004,2006) ~ "2004-2006",
                          between(atc_year, 2007,2009) ~ "2007-2009",
                          between(atc_year, 2010,2012) ~ "2010-2012",
                          between(atc_year, 2013,2015) ~ "2013-2015",
                          between(atc_year, 2016,2019) ~ "2016-2019")) %>% 
  mutate(atc_year = fct_relevel(atc_year, "Before 1998")) %>% 
  mutate(sector=if_else(sector==101,"Prescription medication","Hospital medication"))

dfs <- df %>% group_by(year, atc_year, sector) %>% summarize(cc=sum(cost))

p.data <- merge(dfs,expand.grid(atc_year=unique(dfs$atc_year),
                            year=unique(dfs$year),
                            sector=unique(dfs$sector),
                            stringsAsFactors=F),all.y=T)

pb <- colorRampPalette(brewer.pal(9, "Blues"))
p.data$cc[is.na(p.data$cc)] <- 0

me8 <- p.data %>%
  ggplot(aes(year, cc/1e3, fill=atc_year, group=atc_year)) + 
  scale_fill_manual(values = pb(10)[2:24]) +
  scale_x_continuous(breaks=seq(1997,2019,2)) +
  scale_y_continuous(breaks=seq(0,13000,1000),label = unit_format(unit = "m", sep = "", accuracy = 1))+
  geom_area(color="white", size=0.1) + th1 + 
  facet_wrap(~sector)+
  labs(y="Expenditure", x=NULL, fill="Year introduced") + theme(legend.position = "right")

me8
ggsave(me8, file="plots/me8.pdf", height = 4, width=10, dpi=600)
```



```{r fig.height=2, fig.width=10}
me9 <- data %>% filter(sector==200, substr(atc_code,1,1)=="L") %>% 
  full_join(atc_codes, by="atc_code") %>% 
  group_by(name) %>% 
  mutate(biologic = if_else(str_detect(name,"mab"),T,F)) %>% 
  group_by(year,name) %>%
  summarize(totyr=sum(cost_adj, na.rm=T),
            biologic=first(biologic)) %>% 
  group_by(year) %>% 
  summarize("Biologics"  = sum(totyr[biologic], na.rm=T),
            "Chemical drugs" = sum(totyr[!biologic], na.rm=T)) %>%  
  gather(variable, value,-year) %>% 
  ggplot(aes(year,value, fill=fct_relevel(variable, "Chemical drugs"))) + 
  geom_col(position="fill", width=0.7) + 
  scale_y_continuous(label=scales::percent_format())+
  scale_x_continuous(breaks=c(seq(1997,2019,2))) + 
  labs(fill=NULL, y="Percent of total\ncosts", x=NULL) + 
  scale_fill_brewer(palette="Paired") + th1
me9

ggsave(me9, file="plots/me9.pdf", height = 2, width=10, dpi=600)
```




```{r}
ggsave(me1, file="plots/me1.pdf", height = 3,   width = 10,   dpi=600)
ggsave(me2, file="plots/me2.pdf", height = 4.5, width = 10,   dpi=600)
ggsave(me2a,file="plots/me2a.pdf",height = 4.5, width = 10,   dpi=600)
#ggsave(me2b,file="plots/me2b.pdf",height = 4.5, width = 10,   dpi=600)
#ggsave(me3, file="plots/me3.pdf", height = 6.5, width = 12,   dpi=600)
ggsave(me5, file="plots/me5.pdf", height = 5,   width = 11.5, dpi=600)
ggsave(me6, file="plots/me6.pdf", height = 6,   width = 12,   dpi=600)
#ggsave(me7, file="plots/me7.pdf", height = 6,   width = 12,   dpi=600)
```





































```{r}
top <- data %>% filter(sector==200) %>% 
  full_join(atc_codes, by="atc_code") %>% 
  group_by(name) %>% 
  summarize(sum = sum(a1_turnover, na.rm=T)) %>% view
```



```{r fig.height=4, fig.width=15}
df <- data %>% filter(sector==101) %>% 
  group_by(atc_code, year) %>% 
  summarize(cost = sum(a1_turnover, na.rm=T)) %>% 
  group_by(atc_code) %>% 
  mutate(atc_year=min(year)) %>% 
  full_join(atc_codes, by="atc_code") %>% 
  group_by(year, atc_year, atc_code, name) %>% 
  summarize(cost=sum(cost, na.rm=T))

top <- df %>% group_by(atc_code) %>% summarize(tot=sum(cost, na.rm=T)) %>% top_n(20,tot) %>% select(atc_code)

dfs <- df %>% group_by(year, atc_year) %>% summarize(cc=sum(cost))

p.data <- merge(dfs,expand.grid(atc_year=unique(dfs$atc_year),
                            year=unique(dfs$year),
                            stringsAsFactors=F),all.y=T)

pb <- colorRampPalette(brewer.pal(9, "Blues"))
p.data$cc[is.na(p.data$cc)] <- 0

p.data %>%
  #filter(atc_year != 1997) %>% 
  ggplot(aes(year, cc/1e3, fill=as.factor(atc_year), group=as.factor(atc_year))) + 
  scale_fill_manual(values = pb(24)[2:24]) +
  scale_x_continuous(breaks=seq(1997,2019,3)) +
  scale_y_continuous(breaks=seq(0,10000,1000),label = unit_format(unit = "m", sep = "", accuracy = 1))+
  geom_area(color="white", size=0.1) + th1 + 
  labs(y="Expenditure", x=NULL, fill="Year introduced")


p.data %>% filter(year %in% c(2018, 2008)) %>% 
  mutate(rel_year=year-atc_year) %>% 
  group_by(year) %>% 
  mutate(pct = cc/sum(cc)*100) %>% 
  group_by(atc_year) %>% filter(between(rel_year, 0,10)) %>% 
  ggplot(aes(as.factor(year), cc, fill=as.factor(atc_year))) + 
  geom_col(color="white", width=0.3, position="fill") + coord_flip() + 
  scale_fill_manual(values = pb(28)[6:27]) + 
  geom_text(aes(label=substr(atc_year,3,4)),position = position_fill(vjust = .5), color="black", vjust=-1, size=3) + 
  geom_text(aes(label=paste0(round(pct,1),"%")),position = position_fill(vjust = .5), color="black", vjust=1, size=3)

```































